import { Roller } from '../utils/Roller';

export function personalCharacteristicsGenerator() {
    return data[Roller.roll(data.length) - 1];
}

const data = [
  'Curses often and apologizes each time.',
  'Picks his fingers with his dagger.',
  'Picks his nose and/or pulls out a nose hair.',
  'Flips a coin and checks how it lands before answering questions.',
  'Constantly pulls on their ear.',
  'Comes close and puts their hands on those they talk to.',
  'Has a cat that always follows and comes when he calls.',
  'Has a lazy eye.',
  'Kisses a token on a necklace often for luck.',
  'Has horrible garlic breathe.',
  'Bows as he speaks in a subserviant manner.',
  'Trys to make jokes and loudly laughs at everything.',
  "Answers every question with another question and thinks he's sly.",
  'Loses track of the conversation as if bored.',
  'Has an eye for one of the characters and leads all conversation towards that.',
  'Puts out his hand for some coing if any question is asked.',
  'Constantly chewing on something.',
  'Offers to buy any material on the characters. Belt, pouch, weapon, offers money for everything.',
  'Constantly looking over their shoulder as if they expect somebody.',
  'Trip often when they walk.',
  "Don't understand anything explained to them.",
  'Agree with anything the characters say.',
  'Twirl a coin between their fingers.',
  'Constantly shuffling cards or rolling dice.',
  'Has conversations with themself.',
  "Uses odd expletives, such as 'Spoon!'",
  'Makes odd random noises.',
  'Cracks their knuckles.',
  'Has a nerveous twitch.',
  'Has two differently colored eyes.',
  'Fingernails are dark green with a fungus.',
  'Their eyebrow hairs closest to their nose are exceptionally long, like antenna.',
  'Has that skin condition that leaves a wine colored stain on thier face.',
  'Shuffles their feet.',
  'Always one hand in their pocket.',
  'Has a hand stuffed into their shirt, ala Napoleon.',
  'Wants to be bribed by an addition to their unusual collection, like odd hats or the big toes of unusual creatures.',
  'Sucks eggs.',
  'Eats peanuts in the shell and the shell too.',
  "Has a catch phrase that makes no sense, like 'Ice cream can!' or 'Oranges don't dance.'",
  'Has a hairless pet that they dress up and fawn over.',
  'Has a spoon they keep in their mouth and treats like a pipe.',
  'Always manages to be eating some type of pie.',
  'Dances for any reason whatsoever.',
  'Pops nuts or small fruits off their bicep to catch them in their mouth.',
  'Chokes on anything they drink.',
  'Has a strange allergic reaction, like hives from copper, or alchohol gives them a rash.',
  "Makes a nickname for everyone and most objects as well. Calls spoons 'soup shovels', calls knives 'sharpie-sharps', gold 'pretty pennies', etc.",
  'Passes gas out of hand.',
  'Has an exotic drink with something alive in it. Like a fish or small octopus, maybe a frog or snake.',
  'Puts a small umbrella in everthing edible. Drinks, sandwiches, soup, fruit, crackers, cheese, anything.',
  'Hiccups.',
  'Horrible scarred/burned face and hands.',
  'Walks with a limp and a cane.',
  'Talks in a whisper.',
  'Missing all front upper teeth.',
  'Expert rat catcher, even in the middle of conversations will jump or chase a rat if he sees it.',
  'An unbalanced drunk, always falling or tipping.',
  "Calls everyone Skipper. Chappy. Cap'n. Lala.",
  'Has inside of coat full of trinkets and small jewelry for sale.',
  'Knows some nice ladies that would love to meet you.',
  'Sings the sentences.',
  'Missing an ear. leg. foot. arm... ',
  'Talks like a pirate. Arrrgh.',
  "Knows everybody of 'inconsequence' and is constantly interrupted by saying hi to people.",
  'Talks like austin powers.',
  'Wears an unusual medical device, like some headgear attatched to thier nose instead of braces on thier teeth, or a glove with fingertips a foot long.',
  'Tends to put or keep things up their nose.',
  "Is oblivious to the fact they're indecently exposed.",
  'Has a club limb.',
  "Has an extensive tattoo that seems out of place on thier person, example fat pink bunny on a bouncer, or a city offical with a winged skull on their hand's webbing.",
  'Runs into things.',
  'Has six fingers on their right hand (Hello! I am Inego Montoya!)',
  'Is unaware they have a tattoo on thier forehead.',
  'Goes crosseyed when excited.',
  'Has teeth filed to points.',
  'Ears wiggle uncontrolably when lying.',
  'Carves small vegetables with remarkable skill into people, animals, and things, then smashes and eats them.',
  "Has a small corner of a printed circuit board for an earring; swears it's some kind of shale and an old family heirloom.",
  'Keeps unsuccessfully trying to make jokes about dead animals.',
  'Has one (green, purple, red, orange) finger.',
  'Has a cloak kept closed with a strip of wool and split burr shells.',
  "Can't stand being asked the same question three times.",
  "The joints of one limb occasionally freeze and can only be used again after they're beaten.",
  'Is missing both hands and feet.',
  'Has a ludicrously long nose.',
  'Has a parrot-like nose.',
  'Keeps slaves on a chain behind them.',
  'Has lost an eye and replaced it with a gem.',
  'Has a bone pierced through their nose.',
  'Has shining white teeth.',
  'Believes to be an illegitimate child of someone important (maybe even a king or god).',
  'Is an illegitimate child of someone important (maybe even a king or god).',
  'Believes that is cursed in some way.',
  'Scratches his head/beard/body_part often.',
  'Obsessed with diets and weight loss.',
  'Considers himself extremely smart, and tries to show it.',
  'Does not like physical contact with others.',
  'Non-stop fresh and full of energy.',
  'Does not like too bright sun, likes the shadow more.',
  'Sharp-eyed, seems to notice everything that happens around.',
  'If unmoving for some time, must stretch a bit, bones cracking loudly (only a sound).',
  'After stressfull situations needs to be alone for a while.',
  'Likes a certain animal above all, example for everyone!',
  'Talks with his dead relative/friend.',
  'Considers himself a very impressive individuum.',
  'Must always have the last word.',
  'Has mystical ability of comunnicating with drunks, meaningfully.',
  'Extremely picky with food.',
  'Pretends nothing can harm him.',
  'Looks sleepy, yawns... (watch out, contagious).',
  'Has very heavy/noisy steps.',
  'Resembles in some ways a monkey.',
  'Has a supernatural talent, but tries to hide it and get rid of it.',
  'Feels the need for a True Love.',
  'It is unacceptable for a person of this position to get drunk, but would like so much...',
  'Is/was a master of some bizzare local sport.',
  'Is a secret follower of some god/cult/organisation, that is not in the the least way secret.',
  'Did not want this kind of life, but got no chance. Will complain about it.',
  'Promises revenge for all evil done to him.',
  'Looks malnourished',
  'Likes to play with fire! No pyromaniac, just toying with, looking into fire, etc.',
  'Unevenly grown beard that he constantly scratches.',
  'Does everything with a flourish.',
  'Wishes he was a royal and is jealous of those that are.',
  'Merchant minded and always looking for a new angle.',
  'Keeps checking in his pocket for something like making sure it is still there.',
  'Has a wooden staff that he is constantly rubbing or using to lean on.',
  'Large hat that he is constantly taking off and putting back on.',
  'Wears shirt that is too small and the buttons are bulging and belly hanging out.',
  'No belt and constantly pulling up their pants.',
  'Chewing on a stick.',
  'Wishes to purchase some farm land and retire.',
  'Has some black market goods for sale.',
  'Very inquisitive about everything. Wants every detail.',
  'Looking to learn a talent that the PC has. Willing to pay for it.',
  'Asks about contacts or people to see in different cities.',
  'Very interested in a previous NPC that the PC has met. Owes money?',
  'Very interested in an item on the PC, looking to get one of their own.',
  'Suggests that the PC smells and needs a bath in subtle or unsubtle terms.',
  'Insanely paranoid.',
  'Is not paranoid, because some one or thing is really after them.',
  "Acts insane around people he doesn't like.",
  'Acts insane around strangers.',
  'Acts insane around people in general.',
  'Acts like a drooling idiot for unknown reasons.',
  'Constantly hums or sings off key.',
  'Is constantly fiddling with comething.',
  'Treats any and all creatures as sentient, whether they are or not.',
  'Treats any and all objects as sentient.',
  'Is afraid of dust.',
  'Is obsessive compulsive.',
  'Consantly speaking in riddles.',
  'Yells out everything.',
  'Freaks out over some small, common item or detail.',
  'Constantly spewing useless and/or gross facts.',
  'Perma-scowl (always scowling).',
  'Instantly hates a person for no good reason and knows it.',
  'Believes they are a miniature giant.',
  'Extremely egoistical.',
  'Constantly running schemes past people.',
  'Punches/kicks people for small mistakes.',
  'Always tells lies.',
  'Asks random people if they are willing to be a sacrifice for an obscure deity.',
  'Wants a pet ooze/slime.',
  "Thinks they're a legandary hero suffering from a geas (may or may not be true).",
  'Constantly twirls a gold coin between his fingers.',
  'Hasn�t bathed forever and is very smelly.',
  'Tendency to stare evenly at attractive women.',
  'Squints often.',
  'Hums under his breath at odd times.',
  'Loves animals more than people.',
  'Enjoys eating raw onions.',
  'Mutters to himself when frustrated with others.',
  'Moves as if sneaking about even in daylight with people around.',
  'Has some magic beans given to him by his mother.',
  'Drinks only water.',
  'Annoying melancholy and negative.',
  'Never smiles.',
  'Spits often as a curse.',
  'Refers to most others as boy or lass untill they prove themselves.',
  'Has an intricate tribal tatoo covering his back -very secretive about it.',
  'Cleans fingernails with his dagger.',
  'Makes throaty growling noises.',
  'Has pierced eyebrows.',
  'Aversion to heat.',
  'Aversion to light',
  'Aversion to certain animals (e.g. insects, magpies, frogs).',
  'Tendency to ask stupid questions.',
  'Narcoleptic/cataleptic.',
  "Constantly makes reference to things which seem random at the time but which later turn out that he could never have known because they hadn't happened yet (e.g. is humming the main theme from an opera the day before its premiere, talks about King John when the current reigning monarch is King Fred who later that day abdicates in favour of his younger brother, John)",
  'Licks walls (not as uncommon as it may sound)',
  'Absent-mindedly waggles leg/hand at a speed which varies with how excited they are',
  'Laughs very loudly, looks very incongruous and yet appears all over the place. The PCs never get the chance to speak to him or even find out who he is.',
  'Always seen sitting in the same place. He is never seen anywhere else.',
  'Has an irrational fear of the number 14.',
  'Tendency to stop half-way through a sentence, pause then go back and correct himself.',
  "Always wears a scarf wrapped tightly around his neck, even indoors. It could be he's cold, or there might be something more sinister... ",
  "Is only short but somehow dominates the room. Maybe it's the piercing eyes.",
  'Has an obsession with making their own clothes. As a result their clothes are tatty.',
  'Impulsively counts things (e.g. number of bricks in a wall, number of words in a sentence).',
  'Always knows better',
  "Finishes sentences with 'so...' (e.g. 'I've been to the King and he said yes, so...').",
  'Spells out words before he/she S-A-Y-S says them.',
  "Giggles when he/she hears random words, saying: 'That's dirty!' ",
  'During pauses in the conversation, he/she gazes longingly in the direction of a man/woman across the room.',
  'He/she trails of in the middle of an important sentence and wanders away. If pursued, he/she will turn around and start again where he left off.',
  'Repeats a key word of every person that he hears speak and nods as if in agreement.',
  'Relieves himself wherever it is convenient for him. (nearest wall, darkest corner, behind a fruit stand).',
  "Doesn't wear shoes. (applies to races that do anyway, wears shoes for races that don't).",
  'Constantly picks a scab causing it to bleed.',
  "Yells 'IA Cthulhu' at random intervals.",
  "Carries a wand. Doesn't do anything with it, but he is always fidgeting with it. When asked about it he will grunt out incoherencies and change the subject.",
  'Compares everything to the days of youth, when everything was so much better, and the world was not as it is today, and...',
  'Before actually talking to someone, scans carefully their footprints first.',
  'Claims to be able to Detect Lies.',
  'Offers a nice sum in gold if they do _not_ talk to him.',
  'Orienteering-disabled, has a hard time to navigate own village or town, cannot show way to any place.',
  "Occassionaly makes rapid moves or something a bit unexpected, only to say: 'Now that was a surprise, huh?'",
  'Is wearing a costume of some ancient hero, and tries to play him/her to the smallest detail.',
  'Immersed into a new fascinating philosophy involving meditating in trance, tea rituals, etc.',
  'Plans to write a book about the inevitable fall of this civilisation.',
  'An artistic soul, seeks beauty in the ugly things (and people). Like you.',
  'Stays always very brief, all sentences cuts as short as possible.',
  'Whatever they say, it confuses him even more.',
  'Avoids any kind of personal contact, is terribly afraid of poisoning or getting dirty or catching some disease.',
  'Writes everything into a little notebook.',
  'Has found something valuable, and asks if you did not loose it, but will start to raise doubts, should you agree.',
  'Has just paid the taxes or a loan, and complains everywhere on the terrible rates, that this is practically thievery, etc.',
  'An up-and-coming activist, wants to change some obscure and little used law for even more obscure reasons. And you could help!',
  'Is an escaped prisoner, in stolen clothes, and looks for a place to hide.',
  'Loves to invent and tell spooky stories, anytime.',
  "Asks you to become a 'dummy', for some unpleasant activity, like self-defense training.",
  'Threatens to commit suicide if this continues.',
  'Dodges questions, with the body at least.',
  'Sneezes without covering the mouth.',
  'Socks keep falling down so has to keep pulling them up.',
  "Feet stink but doesn't notice. ",
  'Can predict the weather with perfect accuracy.',
  "Collects hair from everybody he meets. Has braids tied all over himself from hair he has 'borrowed.' ",
  'Has a talent for finding wild potatoes and can cook them like nothing you have ever tasted.',
  'Startlingly begins to shout in MIDDLE OF THE SENTENCE.',
  "Irritatingly modest, even about things that he/she had nothing to do with. ('Oh, you don't have to congratulate me about that!' 'Uh... Well, that's fine, because we weren't going to.')",
  'Scratches and claws at his/her scalp in a distracting manner.',
  'Spits out unidentifiable bits of mush during lulls in conversation.',
  'Becomes noticeably angry for no reason. (Could be used as a red herring in mystery-solving adventures.)',
  'Mutters or mouths words to him/herself after he/she is done speaking.',
  'His/her eyes water constantly, making him/her look miserable and sad.',
];
