import { Roller } from '../utils/Roller';

export function sidePlotGenerator(): string {
    return data[Roller.roll(data.length) - 1];
}

const data = [
  'Is feuding with neighbor over grazing rights ',
  'Is a wandering amateur chef looking for new recipes and ingredients ',
  'Is a failed adventurer with much emotional baggage who seeks to sabotage other adventurers ',
  'Is a shrewd negotiator, but offers extremely valuable information in trade for new information ',
  'Is quiet, brooding, and short tempered due to medical problems ',
  'Is a pacifist who tries to convert the party to the ways of non-violence ',
  'Has a racial enemy or is banned from racially dominant areas ',
  'Fears being alone because of a recent incident ',
  'Is collecting parlor games from across the lands ',
  'Tries to recruit the PCs for some incredibly mundane task (i.e. labourer) regardless of PC objections ',
  "Knows of 'lots of great adventures' that are, unfortunately, all dead ends ",
  'Is a historian, but all the facts are invented (compulsive liar) ',
  'Is a travelling madam with company, seeking new employees and better (wealthier) company ',
  'Is recruiting for the military or a special guild ',
  'Is an outcast for forgotten crimes ',
  'Is collecting donations for a charitable fund ',
  'Is looking for a particular person with critical spell components ',
  'Is on a secret military mission ',
  'Is in disguise (for reasons real or imaginary) ',
  'Imagines he/she is a ghost in spite of attempts to prove he/she is living ',
  "Believes (loudly) that wealth should be spread among all the citizens and tries to redistribute the PCs' wealth ",
  'Is paranoid and over-protective of their town ',
  'Is tracking down a villain and vows to kill him/her/it ',
  'Has an unhealthy obsession with another person ',
  'Is good-aligned and has recently run away from evil parents ',
  'Likes to play practical jokes on party members (without revealing culpability if possible) ',
  'Is celibate/chaste, but always attracts the opposite sex ',
  'Is the bastard son of a famous lord (hates his father; half-brothers would kill him on sight) ',
  'Myopic guard -- extremely nearsighted but compensates with well developed sense of hearing ',
  'Is a binge drinker who tends to get in trouble due to violent, drunken bouts ',
  'Trying to find lost love (who is a traveling with a troop of entertainers) ',
  'Spy keeping tabs on party for local leader or powerful NPC ',
  'Extremely lucky (never seems to do anything right, but somehow escapes any personal consequences) ',
  "A 'wanted man' sought by a particular non-human good race (i.e. Elves, Halflings, Dwarves, etc.) for some past misdeed or misunderstanding ",
  "Greedy -- always demands first dibs and/or larger shares when dividing treasure troves based on exaggerated contributions to the party's success ",
  'Is unhappily married and will do anything to get out of it ',
  'Is a fan (to the point of fanaticism) of a spectator sport of the time (jousting, cockfighting, bearbaiting, whatever) and has gotten into gambling/stalking trouble ',
  'Is heavily in debt and is fleeing/hiding from creditors ',
  'Is an outspoken advocate of a controversial political position ',
  'Is an aspiring bard and uses the PCs as subjects of his/her newest songs without their consent ',
  'Is one of the top artisans at his/her craft, but circumstances beyond his/her control have forced him out of the trade ',
  'Is a proud parent and wants his/her child to become an adventurer ',
  'Was adopted as an infant and is in search of his/her bio- parents ',
  'Is an outcast in the community for no good reason ',
  'Is a self-proclaimed matchmaker and tries to set up at least one of the PCs ',
  'Is an unwitting thrall to a powerful vampire ',
  'Is searching for a lost family heirloom -- the heirloom may not have any value other than sentiment ',
  'Is on a personal quest for enlightenment, salvation, vengeance, atonement, etc. ',
  'Is on a personal quest for power and has made dark pacts with evil outsiders to accomplish this end ',
  'Is a vigilante who kills in cold blood convinced that the ends (i.e. eliminating a criminal element) justify the means (using excessive force, killing hostages, etc.) ',
  'Is the reluctant heir to some ancient, forbidding, or dark power ',
  'Will deal with the PCs only in a specific, non-monetary currency (i.e. gems, jewels, fine art, old whiskey, etc.) ',
  "Wants the PCs to 'accidentally retrieve' an item while they are investigating clues ",
  'Is tainted in some way and tries at all costs to keep the taint a secret ',
  "Wants the PCs to deliver a letter to his mother - but he doesn't know that his mother is really that cackling night hag that the local lord wants hunted down and exterminated ",
  "Wants PCs to 'lend' him the main plot item after they retrieve it, before they hand it over to the main plot instigator. The motivation could be pure (i.e. item needed to lift a deadly curse) or nefarious (i.e. item used to raise an army of undead) ",
  'Suffers from a skin condition which causes his skin to burn and peel in direct sunlight -- but is not a vampire ',
  'Is a doctor who unwittingly spreads a deadly plague even while trying desperately to find the cure ',
  'Suffers from black-outs and is completely unaware of his actions, during the black-out ',
  'Is an unsuccessful playwright who has stolen the latest creation of a very well known bard ',
  "Is deadly terrified of shadows. He'll only meet with the PCs in places completely devoid of shadows ",
  'Has a craving for rare herbs and spices that unknown to the PCs are used to create a powerful narcotic ',
  'Is lecherous and married. Asks the PCs for help sneaking in and out of brothels ',
  'Is a voyeur who happens to be spying on the house where the PCs are adventuring ',
  'Is a worshipper of a death god(dess) or a necromancer who wishes to serve as a mortician of the city but needs documents proving his/her good intentions/standing ',
  'Is extremely obese and is attempting to travel a long distance ',
  "Thinks he's a duck because of a powerful enchantment ",
  'Is an anarchist attempting to recruit followers to overthrow the government ',
  'Has recently broken up with a lover and now laments ',
  'Is pregnant and the father is a noble/priest/etc. ',
  'Cannot stop complaining, and will complain to anyone near them but knows key information hidden among the complaints ',
  "Has an irrational fear of pants and attempts to 'save' anyone who happens to be wearing pants ",
  'Sells rice cakes with magic rings inside ',
  'Tries to pass off lousy equipment as magical ',
  'Sells magical equipment that looks fake or non-magical ',
  'Is a lowly beggar with friends in high places who acts as a spy for a powerful wizard or guild ',
  'Sells rare and unusual spells ',
  'Is the most annoying person in town but befriends the PCs ',
  'Is trying to ditch the city guards, who are chasing him for a minor crime ',
  'Has had an operation to change his/her race, but still manifests cultural mannerisms of his/her original race ',
  'Used to be a powerful adventurer ',
  'Is promoting a new religion and tries to convert all who pass by ',
  'Is an artist trying to sell his works ',
  'Is a writer trying to sell his works ',
  'Is a noble trying to swap places with a peasant for a day ',
  'Is a very trusting foreigner ',
  'Acts as a local guide to the PCs ',
  'Has distinctly disproportionate limbs (i.e. one arm longer than the other, etc) that were altered through magic ',
  'Is a rich tax collector targeted by several opponents who feel that he/she is unfair or embezzling ',
  'Acts as a representative for the Black Market ',
  'Desperately needs an item only available through the Black Market ',
  'Is a disgruntled worker recently laid off ',
  'Is part of a group of traveling musicians seeking a benefactor ',
  'Believes that he is the only voice of a powerful god ',
  'Rants uncontrollably about unrelated things as if under the effects of a Feeblemind ',
  'At first sight, falls madly in love with one of the party members and becomes obsessive/stalks ',
  'Is in the process of creating their own masterpiece (painting, pottery, sculpture, etc.) and wants to use one of the PCs as a model/inspiration ',
  'Is an opera house maestro who mistakes one of the PCs for the lead in his production and whisks them off to perform ',
  'Believes that one of the party members is a long lost relative ',
  'Is trying to marry off their eldest son/daughter to one of the PCs ',
  'Is being held captive in his/her own home ',
  'Has been replaced by a doppleganger ',
  'Is seeking political/religious asylum ',
  'A bitter rival was just elected into a minor position and NPC wants to ruin his reputation ',
  'NPC is a victim of spousal abuse ',
  'NPC has invented a new piece of equipment and is looking for a test subject ',
  'NPC is seeking support and election for a minor bureaucratic position with a long title ',
  'Is a guard or law official who seeks information about who, how and why he was framed for a crime that resulted in his dismissal ',
  'Is desperately trying to join a prestigious sports team/league ',
  'Is trying to find out how to join a certain secret cult ',
  'Is seeking his muse ',
  'NPC is squatting and claims an ancient family right to the site ',
  'Is looking for his/her father who disappeared in the area 6 months ago ',
  'Seeks his/her father/mother/child who ran away from home ',
  'NPC seeks an ex-lover to claim child-support for their bastard child ',
  'Is going out at night and mistreating stray animals ',
  'Was recently injured in a random attack and seeks his attackers for revenge ',
  'Is hiding from local elves who seek him after recently telling several off-colour elven jokes in public ',
  'Is trying to fulfill a bizarre request of their employer, but with no luck ',
  "Is an informant for the local thieves' guild with nothing to report and is ready to make something up ",
  'Loudly and publicly complains about the local lord ',
  'Is looking for a business partner ',
  "Is a barber who's invented a new hairstyle and is looking for customers ",
  "NPC's home burnt down last night ",
  'NPC is a merchant looking to open trade with other races and spot a non-human PC ',
  'NPC has an injury or disease and is saving up for a heal spell ',
  'A meek NPC has a valuable treasure but does not know who to turn to and trust for the sale ',
  "Is a skilled amateur gambler looking to break into the pros or find the 'big game' ",
  'Has been falsely accused and has just posted bail and is now looking for proof of his innocence ',
  "Fears he's being watched and is looking for someone who he can trust to recover a valuable object buried nearby ",
  'NPC is looking to buy winter clothing and bedding for their orphanage but wool prices are up due to a local shortage ',
  'Is trying to drink himself to death ',
  "Has been given a task by his boss and his boss would punish him if it was known he was 'wasting time' with the PCs ",
  'Wants the PCs to promote her business by wearing or using her product prominently whenever possible (fashionable cloaks, very tasty trail rations, a specific musical instrument, etc.) ',
  'Pumps the characters for details about their exploits, then goes around claiming that he himself did these things ',
];
